/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import org.echoserver.EchoServer;

public class AppTest {
    @Test public void appHasAGreeting() {
        EchoServer classUnderTest = new EchoServer(200);
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
